[project]
name = "s-sdtm-ai"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.120.3",
    "pandas>=2.3.3",
    "rpy2>=3.6.4",
    "sse-starlette>=3.0.3",
    "uvicorn>=0.38.0",
]
